// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
precachemodel("zombie_dog");
precachemodel("zombie_dog_a");
precachemodel("zombie_dog_b");
precachemodel("zombie_dog_c");
	self setModel("zombie_wolf");
	self.voice = "american";
	self.skeleton = "base";
}

precache()
{
	precacheModel("zombie_wolf");
}
